version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    container_name: doctor_db
    environment:
      POSTGRES_USER: docuser
      POSTGRES_PASSWORD: docpass
      POSTGRES_DB: docdb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready -U docuser -d docdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: doctor_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://docuser:docpass@db:5432/docdb
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  db_data: